# Generated by Django 4.1.13 on 2023-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('s3_url', models.URLField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
